const books = [
    {
        id: 1,
        author: "Jordan Peterson",
        image:"https://images-na.ssl-images-amazon.com/images/I/41EATHVLJRL._SX324_BO1,204,203,200_.jpg",
        title: "12 Rules for Life: An Antidote to Chaos",
        slug: "12-rules-for-life:-an-antidote-to-chaos",
        genre: ["Self-Help"],
        available: false,
        borrowedBy: [3],
      },
      {
        id: 2,
        author: "Blake Crouch",
        image:"https://images-na.ssl-images-amazon.com/images/I/81X6jSuxZ1L.jpg",
        title: "Dark Matter",
        slug: "dark-matter",
        genre: ["Sci-Fi", "Thriller"],
        available: false,
        borrowedBy: [3],
      },
      {
        id: 3,
        author: "Robin Sloan",
        image:"https://d2wzqffx6hjwip.cloudfront.net/spree/images/attachments/000/024/177/original/9781922079169.jpg?1502236605",
        title: "Mr. Penumbra's 24-Hour Bookstore",
        slug: "mr.-penumbra's-24-hour-bookstore",
        genre: ["Suspense", "Fantasy"],
        available: false,
        borrowedBy: [1, 3, 5, 1],
      },
      {
        id: 4,
        author: "Paul Kalanithi",
        image:"https://images-na.ssl-images-amazon.com/images/I/91iZ2ZQduBL.jpg",
        title: "When Breath Becomes Air",
        slug: "when-breath-becomes-air",
        genre: ["Biography"],
        available: true,
        borrowedBy: [2, 5],
      },
      {
        id: 5,
        author: "Eric Ries",
        image:"https://images-na.ssl-images-amazon.com/images/I/81vvgZqCskL.jpg",
        title: "The Lean Startup",
        slug: "the-lean-startup",
        genre: ["Business", "Entrepreneurship"],
        available: false,
        borrowedBy: [4, 1, 2],
      },
      {
        id: 6,
        author: "George R.R. Martin",
        image:"https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/0064/9780006479901.jpg",
        title: "A Storm of Swords",
        slug: "a-storm-of-swords",
        genre: ["Fantasy"],
        available: true,
        borrowedBy: [],
      },
      {
        id: 7,
        author: "Leigh Bardugo",
        image:"https://cdn.shopify.com/s/files/1/0458/6386/2439/products/sixofcrows.jpg?v=1609441778",
        title: "Six of Crows",
        slug: "six-of-crows",
        genre: ["Fantasy"],
        available: false,
        borrowedBy: [4, 3, 2, 1, 5],
      },
      {
        id: 8,
        author: "Agatha Christie",
        image:"https://d3525k1ryd2155.cloudfront.net/h/518/893/1148893518.0.l.jpg",
        title: "Curtain: Poirot's Last Case",
        slug: "curtain:-poirot's-last-case",
        genre: ["Crime", "Mystery"],
        available: false,
        borrowedBy: [3, 5],
      },
      {
        id: 9,
        author: "Elif Shafak",
        image:"https://images-na.ssl-images-amazon.com/images/I/91Q4lLuogQL.jpg",
        title: "The Forty Rules of Love",
        slug: "the-forty-rules-of-love",
        genre: ["Fiction"],
        available: false,
        borrowedBy: [5, 1],
      },
      {
        id: 10,
        author: "Leigh Bardugo",
        image:"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1491842507l/34076952.jpg",
        title: "The Language of Thorns: Midnight Tales and Dangerous Magic",
        slug: "the-language-of-thorns:-midnight-tales-and-dangerous-magic",
        genre: ["Fantasy"],
        available: false,
        borrowedBy: [5],
      },
    ];




export default books